[package]
publish = false
edition = "2021"
name = "xtask"
version = "0.0.0"
authors = ["silvanshade <silvanshade@users.noreply.github.com>"]

[features]
debug = []
default = []

[dependencies]
cxx-auto-xtask = { git = "https://github.com/silvanshade/cxx-auto-xtask", rev = "3d44dea" }
